### ISSUE TITLE
Track Roomba's position

### ISSUE THREAD

**Issue by rurounijones** [tokyorails/rrroomba#3]
I have added some code which I think should work and allow use to track the current coordinates of a roomba.

https://gist.github.com/2326019
- Added x,y,facing to initialise
- added update_position method
- added code to the move method at lines 36, 41, 46

Because I cannot test this and the simulator code is totally different (Haven't figured out how to go about changing the simulator code to match this) could someone have a look at this and check what I have written?

**Comment by cwabbott** [comment]
Going to check this out today and will let you know :)

**Comment by rurounijones** [comment]
Ahoi Charles, were you able to check this? Did it work as expected (I don't see why it wouldn't but hey).

If it does then I shall see if I can get it working in the simulator as well but I am still getting my head around how that has been designed.

**Comment by cwabbott** [comment]
I'm going to mark Roomba's starting point, move him around a bit, then move him until x,y are back at 0,0 to see if Roomba has returned to that marked starting point. Do you have any suggestion for a better test?

I'm certain, though, that my implementation of the degree / arc is wrong and I'm working on an update there (so this might affect the results of this test).

As for the simulator, I'll brush that up with some better explanations. I'm sure it needs some updates as well.

**Comment by rurounijones** [comment]
Nope, that test sounds fine. I would also like to see how accurate it is at reporting position after hitting something.

The reason I want the position information is so that I can build up a graph of navigable nodes for future path-finding. Basically we send Roomba around a square pseudo-randomly and it will save navigation nodes every x seconds (or distance, haven't decided) or when it bumps into something.

That is why I have the relatively convoluted "How much distance did it REALLY travel" code instead of just assuming it reached the point we told it to go to.

I know it won't sync 100% but as long as the sync loss isn't too fast then I think we can run with it. If it loses sync very quickly then it is back to the drawing board.

**Comment by cwabbott** [comment]
By the way, I left a comment under the gist code. I couldn't get it to go back to 0,0, even after driving the Roomba back to its original physical location. I'll be testing code with Roomba again tomorrow for most of the day, maybe we can find the culprit by then.

**Comment by rurounijones** [comment]
Ahoi charles, I have some friends visiting from UK this weekend so don't have any time to look at this until Tuesday at the earliest. Will check stuff then.
